version: "3.9"
services:
  prometheus:
    image: prom/prometheus:v2.53.0
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/alerts.yml:/etc/prometheus/alerts.yml:ro
    command: ["--config.file=/etc/prometheus/prometheus.yml","--web.enable-lifecycle"]
    ports: ["9090:9090"]
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager:v0.27.0
    ports: ["9093:9093"]
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.4.5
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana:/var/lib/grafana
    ports: ["3000:3000"]
    restart: unless-stopped

  node_exporter:
    image: prom/node-exporter:v1.8.2
    network_mode: host
    pid: host
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports: ["8080:8080"]
    restart: unless-stopped

  dcgm_exporter:
    image: nvidia/dcgm-exporter:3.3.6-3.5.0-ubuntu22.04
    runtime: nvidia
    ports: ["9400:9400"]
    restart: unless-stopped
